import React from "react";
const destinations = [
  {
      id: 1,
          city: "Dubai",
              country: "United Arab Emirates",
                  image:
                        "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=80",
                            hotels: "180 Luxury Hotels",
                                price: "$420",
                                  },
                                    {
                                        id: 2,
                                            city: "Paris",
                                                country: "France",
                                                    image:
                                                          "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1200&q=80",
                                                              hotels: "210 Premium Hotels",
                                                                  price: "$360",
                                                                    },
                                                                      {
                                                                          id: 3,
                                                                              city: "Tokyo",
                                                                                  country: "Japan",
                                                                                      image:
                                                                                            "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
                                                                                                hotels: "195 Luxury Hotels",
                                                                                                    price: "$390",
                                                                                                      },
                                                                                                        {
                                                                                                            id: 4,
                                                                                                                city: "Santorini",
                                                                                                                    country: "Greece",
                                                                                                                        image:
                                                                                                                              "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=1200&q=80",
                                                                                                                                  hotels: "90 Boutique Resorts",
                                                                                                                                      price: "$480",
                                                                                                                                        },
                                                                                                                                          {
                                                                                                                                              id: 5,
                                                                                                                                                  city: "Maldives",
                                                                                                                                                      country: "Maldives",
                                                                                                                                                          image:
                                                                                                                                                                "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=1200&q=80",
                                                                                                                                                                    hotels: "75 Private Resorts",
                                                                                                                                                                        price: "$890",
                                                                                                                                                                          },
                                                                                                                                                                            {
                                                                                                                                                                                id: 6,
                                                                                                                                                                                    city: "New York",
                                                                                                                                                                                        country: "United States",
                                                                                                                                                                                            image:
                                                                                                                                                                                                  "https://images.unsplash.com/photo-1499092346589-b9b6be3e94b2?w=1200&q=80",
                                                                                                                                                                                                      hotels: "320 Luxury Hotels",
                                                                                                                                                                                                          price: "$430",
                                                                                                                                                                                                            },
                                                                                                                                                                                                            ];
                                                                                                                                                                                                            export default function Destinations() {
                                                                                                                                                                                                              return (
                                                                                                                                                                                                                  <section className="py-24 bg-white">
                                                                                                                                                                                                                        <div className="max-w-7xl mx-auto px-6">
                                                                                                                                                                                                                                <div className="text-center mb-16">
                                                                                                                                                                                                                                          <p className="uppercase tracking-[0.35em] text-blue-700 font-semibold mb-3">
                                                                                                                                                                                                                                                      Explore The World
                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                          <h2 className="text-5xl font-black text-slate-900">
                                                                                                                                                                                                                                                                                      Popular Destinations
                                                                                                                                                                                                                                                                                                </h2>
                                                                                                                                                                                                                                                                                                          <p className="text-slate-500 text-lg mt-5 max-w-3xl mx-auto">
                                                                                                                                                                                                                                                                                                                      Discover unforgettable destinations and book premium stays in the
                                                                                                                                                                                                                                                                                                                                  world's most iconic cities and tropical escapes.
                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                            <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-8">
                                                                                                                                                                                                                                                                                                                                                                      {destinations.map((place) => (
                                                                                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                                                                                                key={place.id}
                                                                                                                                                                                                                                                                                                                                                                                                              className="group rounded-3xl overflow-hidden shadow-lg hover:shadow-2xl transition duration-300 bg-white"
                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="overflow-hidden">
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <img
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          src={place.image}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            alt={place.city}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="w-full h-72 object-cover group-hover:scale-110 transition duration-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="p-7">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex justify-between items-center mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-blue-700 font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {place.country}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-yellow-500 font-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ⭐ 4.9
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3 className="text-3xl font-black text-slate-900">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {place.city}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-slate-500 mt-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {place.hotels}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex justify-between items-center mt-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-slate-500 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          From
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h4 className="text-3xl font-black text-blue-700">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {place.price}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button className="bg-blue-700 hover:bg-blue-800 transition text-white px-6 py-3 rounded-xl font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Explore
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }