import React from "react";
const hotels = [
  {
      id: 1,
          name: "Burj View Palace",
              city: "Dubai, UAE",
                  image:
                        "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=80",
                            rating: 4.9,
                                price: 420,
                                  },
                                    {
                                        id: 2,
                                            name: "Paris Royal Suites",
                                                city: "Paris, France",
                                                    image:
                                                          "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200&q=80",
                                                              rating: 4.8,
                                                                  price: 360,
                                                                    },
                                                                      {
                                                                          id: 3,
                                                                              name: "Tokyo Sky Hotel",
                                                                                  city: "Tokyo, Japan",
                                                                                      image:
                                                                                            "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&q=80",
                                                                                                rating: 4.9,
                                                                                                    price: 390,
                                                                                                      },
                                                                                                        {
                                                                                                            id: 4,
                                                                                                                name: "London Grand",
                                                                                                                    city: "London, United Kingdom",
                                                                                                                        image:
                                                                                                                              "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=1200&q=80",
                                                                                                                                  rating: 4.8,
                                                                                                                                      price: 410,
                                                                                                                                        },
                                                                                                                                        ];
                                                                                                                                        export default function FeaturedHotels() {
                                                                                                                                          return (
                                                                                                                                              <section className="py-24 bg-slate-50">
                                                                                                                                                    <div className="max-w-7xl mx-auto px-6">
                                                                                                                                                            <div className="flex flex-col md:flex-row justify-between items-center mb-14">
                                                                                                                                                                      <div>
                                                                                                                                                                                  <p className="uppercase tracking-[0.3em] text-blue-700 font-semibold mb-2">
                                                                                                                                                                                                Luxury Collection
                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                        <h2 className="text-5xl font-extrabold text-slate-900">
                                                                                                                                                                                                                                      Featured Hotels
                                                                                                                                                                                                                                                  </h2>
                                                                                                                                                                                                                                                              <p className="text-slate-500 mt-4 text-lg">
                                                                                                                                                                                                                                                                            Hand-picked luxury stays from the world's finest destinations.
                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                            <button className="mt-6 md:mt-0 bg-blue-700 hover:bg-blue-800 transition text-white px-7 py-3 rounded-xl font-semibold">
                                                                                                                                                                                                                                                                                                                        View All Hotels
                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                  <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-8">
                                                                                                                                                                                                                                                                                                                                                            {hotels.map((hotel) => (
                                                                                                                                                                                                                                                                                                                                                                        <div
                                                                                                                                                                                                                                                                                                                                                                                      key={hotel.id}
                                                                                                                                                                                                                                                                                                                                                                                                    className="bg-white rounded-3xl overflow-hidden shadow-lg hover:shadow-2xl transition duration-300"
                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="relative">
                                                                                                                                                                                                                                                                                                                                                                                                                                              <img
                                                                                                                                                                                                                                                                                                                                                                                                                                                                src={hotel.image}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  alt={hotel.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="w-full h-72 object-cover"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button className="absolute top-5 right-5 bg-white rounded-full w-11 h-11 flex items-center justify-center shadow-lg hover:bg-red-50">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ❤
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="p-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex justify-between items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-yellow-500 font-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ⭐ {hotel.rating}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-sm text-slate-500">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Luxury
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h3 className="text-2xl font-bold text-slate-900 mt-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {hotel.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-slate-500 mt-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      📍 {hotel.city}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex justify-between items-center mt-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-slate-500 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Starting From
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h4 className="text-3xl font-black text-blue-700">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ${hotel.price}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-slate-400 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              per night
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button className="bg-blue-700 hover:bg-blue-800 transition text-white px-5 py-3 rounded-xl font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Book Now
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }