"use client";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
export default function Navbar() {
  const [menuOpen, setMenuOpen] = useState(false);
    return (
        <header className="sticky top-0 z-50 bg-white/95 backdrop-blur-md border-b border-slate-200 shadow-sm">
              <div className="max-w-7xl mx-auto px-6">
                      <div className="flex items-center justify-between h-20">
                                {/* Logo */}
                                          <Link href="/" className="flex items-center">
                                            <Image
                                                src="/logo.png"
                                                    alt="Stayora"
                                                        width={190}
                                                            height={55}
                                                                priority
                                                                    className="h-12 w-auto"
                                                                      />
                                                                      </Link>
                                                                                                    {/* Desktop Navigation */}
                                                                                                              <nav className="hidden lg:flex items-center gap-8">
                                                                                                                          <Link
                                                                                                                                        href="/hotels"
                                                                                                                                                      className="text-slate-700 hover:text-blue-700 transition font-medium"
                                                                                                                                                                  >
                                                                                                                                                                                Hotels
                                                                                                                                                                                            </Link>
                                                                                                                                                                                                        <Link
                                                                                                                                                                                                                      href="/flights"
                                                                                                                                                                                                                                    className="text-slate-700 hover:text-blue-700 transition font-medium"
                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                              Flights
                                                                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                                                                      <Link
                                                                                                                                                                                                                                                                                                    href="/cars"
                                                                                                                                                                                                                                                                                                                  className="text-slate-700 hover:text-blue-700 transition font-medium"
                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                            Cars
                                                                                                                                                                                                                                                                                                                                                        </Link>
                                                                                                                                                                                                                                                                                                                                                                    <Link
                                                                                                                                                                                                                                                                                                                                                                                  href="/packages"
                                                                                                                                                                                                                                                                                                                                                                                                className="text-slate-700 hover:text-blue-700 transition font-medium"
                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                          Packages
                                                                                                                                                                                                                                                                                                                                                                                                                                      </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                </nav>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Desktop Buttons */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="hidden lg:flex items-center gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              href="/signin"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="px-5 py-2.5 rounded-xl border border-slate-300 hover:border-blue-700 hover:text-blue-700 transition font-medium"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Sign In
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            href="/register"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="px-6 py-2.5 rounded-xl bg-blue-700 text-white hover:bg-blue-800 transition font-semibold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Register
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Mobile Menu Button */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={() => setMenuOpen(!menuOpen)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="lg:hidden text-3xl text-slate-700"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ☰
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Mobile Menu */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {menuOpen && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="lg:hidden py-6 border-t border-slate-200">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex flex-col gap-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Link href="/hotels">Hotels</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Link href="/flights">Flights</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Link href="/cars">Cars</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Link href="/packages">Packages</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <hr />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        href="/signin"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="border rounded-xl py-3 text-center"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Sign In
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  href="/register"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="bg-blue-700 text-white rounded-xl py-3 text-center font-semibold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Register
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </header>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }