import React from "react";
const testimonials = [
  {
      name: "Sarah Williams",
          country: "United Kingdom",
              image:
                    "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&q=80",
                        rating: "★★★★★",
                            comment:
                                  "Stayora completely changed the way I travel. Booking was effortless, the hotel exceeded expectations and the service was outstanding.",
                                    },
                                      {
                                          name: "David Kim",
                                              country: "South Korea",
                                                  image:
                                                        "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&q=80",
                                                            rating: "★★★★★",
                                                                comment:
                                                                      "Everything from my flight to my hotel was perfectly organised. I couldn't have asked for a smoother experience.",
                                                                        },
                                                                          {
                                                                              name: "Emily Carter",
                                                                                  country: "United States",
                                                                                      image:
                                                                                            "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=300&q=80",
                                                                                                rating: "★★★★★",
                                                                                                    comment:
                                                                                                          "The luxury recommendations were incredible. Stayora has become my first choice whenever I plan a holiday.",
                                                                                                            },
                                                                                                            ];
                                                                                                            export default function Testimonials() {
                                                                                                              return (
                                                                                                                  <section className="py-24 bg-slate-100">
                                                                                                                        <div className="max-w-7xl mx-auto px-6">
                                                                                                                                <div className="text-center mb-16">
                                                                                                                                          <p className="uppercase tracking-[0.35em] text-blue-700 font-semibold mb-3">
                                                                                                                                                      Guest Reviews
                                                                                                                                                                </p>
                                                                                                                                                                          <h2 className="text-5xl font-black text-slate-900">
                                                                                                                                                                                      Loved By Travellers Worldwide
                                                                                                                                                                                                </h2>
                                                                                                                                                                                                          <p className="text-slate-500 text-lg mt-5 max-w-3xl mx-auto">
                                                                                                                                                                                                                      Thousands of travellers trust Stayora to make every journey
                                                                                                                                                                                                                                  unforgettable.
                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                                                                                                                                                                                                                                                                      {testimonials.map((person) => (
                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                key={person.name}
                                                                                                                                                                                                                                                                                                              className="bg-white rounded-3xl p-8 shadow-lg hover:shadow-2xl transition duration-300"
                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                        <div className="flex items-center gap-5 mb-6">
                                                                                                                                                                                                                                                                                                                                                        <img
                                                                                                                                                                                                                                                                                                                                                                          src={person.image}
                                                                                                                                                                                                                                                                                                                                                                                            alt={person.name}
                                                                                                                                                                                                                                                                                                                                                                                                              className="w-20 h-20 rounded-full object-cover"
                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3 className="text-2xl font-bold text-slate-900">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {person.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-slate-500">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {person.country}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-yellow-500 text-xl mb-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {person.rating}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-slate-600 leading-8 italic">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "{person.comment}"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }