import React from "react";
const services = [
  {
      icon: "✈️",
          title: "Flights",
              description:
                    "Find and compare flights from leading airlines with flexible booking options and competitive fares.",
                      },
                        {
                            icon: "🚗",
                                title: "Car Rentals",
                                    description:
                                          "Reserve reliable vehicles for city trips, business travel or unforgettable road adventures.",
                                            },
                                              {
                                                  icon: "🏝️",
                                                      title: "Holiday Packages",
                                                          description:
                                                                "Enjoy carefully curated holiday packages that combine flights, accommodation and experiences.",
                                                                  },
                                                                    {
                                                                        icon: "🛡️",
                                                                            title: "Travel Insurance",
                                                                                description:
                                                                                      "Travel with confidence thanks to comprehensive protection for your journey and peace of mind.",
                                                                                        },
                                                                                        ];
                                                                                        export default function TravelServices() {
                                                                                          return (
                                                                                              <section className="py-24 bg-white">
                                                                                                    <div className="max-w-7xl mx-auto px-6">
                                                                                                            <div className="text-center mb-16">
                                                                                                                      <p className="uppercase tracking-[0.35em] text-blue-700 font-semibold mb-3">
                                                                                                                                  Complete Travel
                                                                                                                                            </p>
                                                                                                                                                      <h2 className="text-5xl font-black text-slate-900">
                                                                                                                                                                  Everything You Need
                                                                                                                                                                            </h2>
                                                                                                                                                                                      <p className="text-slate-500 text-lg mt-5 max-w-3xl mx-auto">
                                                                                                                                                                                                  Stayora goes beyond accommodation by providing every essential
                                                                                                                                                                                                              service needed for a smooth and memorable journey.
                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-8">
                                                                                                                                                                                                                                                  {services.map((service) => (
                                                                                                                                                                                                                                                              <div
                                                                                                                                                                                                                                                                            key={service.title}
                                                                                                                                                                                                                                                                                          className="bg-slate-50 rounded-3xl p-8 shadow-lg hover:shadow-2xl transition duration-300"
                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                    <div className="text-5xl mb-6">
                                                                                                                                                                                                                                                                                                                                    {service.icon}
                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                <h3 className="text-2xl font-bold text-slate-900 mb-4">
                                                                                                                                                                                                                                                                                                                                                                                {service.title}
                                                                                                                                                                                                                                                                                                                                                                                              </h3>
                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-slate-500 leading-8">
                                                                                                                                                                                                                                                                                                                                                                                                                            {service.description}
                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button className="mt-8 text-blue-700 font-semibold hover:underline">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Learn More →
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }