import React from "react";
const features = [
  {
      icon: "🏨",
          title: "Luxury Hotels",
              description:
                    "Stay in carefully selected luxury hotels, resorts and private villas across the world's most beautiful destinations.",
                      },
                        {
                            icon: "✈️",
                                title: "Best Flight Deals",
                                    description:
                                          "Search and compare flights from trusted airlines while enjoying exclusive Stayora member savings.",
                                            },
                                              {
                                                  icon: "🌍",
                                                      title: "Worldwide Coverage",
                                                          description:
                                                                "Explore thousands of destinations across every continent with one seamless booking experience.",
                                                                  },
                                                                    {
                                                                        icon: "🔒",
                                                                            title: "Secure Payments",
                                                                                description:
                                                                                      "Book confidently with encrypted payments and trusted security protecting every reservation.",
                                                                                        },
                                                                                          {
                                                                                              icon: "⭐",
                                                                                                  title: "24/7 Concierge",
                                                                                                      description:
                                                                                                            "Our travel specialists are available day and night to assist before, during and after your journey.",
                                                                                                              },
                                                                                                                {
                                                                                                                    icon: "💎",
                                                                                                                        title: "Exclusive Rewards",
                                                                                                                            description:
                                                                                                                                  "Unlock member-only discounts, complimentary upgrades and premium travel experiences.",
                                                                                                                                    },
                                                                                                                                    ];
                                                                                                                                    export default function WhyChoose() {
                                                                                                                                      return (
                                                                                                                                          <section className="bg-slate-50 py-24">
                                                                                                                                                <div className="max-w-7xl mx-auto px-6">
                                                                                                                                                        <div className="text-center mb-16">
                                                                                                                                                                  <p className="uppercase tracking-[0.35em] text-blue-700 font-semibold mb-3">
                                                                                                                                                                              Why Stayora
                                                                                                                                                                                        </p>
                                                                                                                                                                                                  <h2 className="text-5xl font-black text-slate-900">
                                                                                                                                                                                                              Why Travellers Choose Stayora
                                                                                                                                                                                                                        </h2>
                                                                                                                                                                                                                                  <p className="text-slate-500 text-lg mt-5 max-w-3xl mx-auto">
                                                                                                                                                                                                                                              Every journey deserves exceptional service. From luxury stays to
                                                                                                                                                                                                                                                          secure bookings, Stayora is designed to deliver unforgettable travel
                                                                                                                                                                                                                                                                      experiences.
                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-8">
                                                                                                                                                                                                                                                                                                          {features.map((feature) => (
                                                                                                                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                                                                                                                    key={feature.title}
                                                                                                                                                                                                                                                                                                                                                  className="bg-white rounded-3xl p-8 shadow-lg hover:shadow-2xl transition duration-300"
                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                            <div className="w-20 h-20 rounded-2xl bg-blue-700 flex items-center justify-center text-4xl mb-6">
                                                                                                                                                                                                                                                                                                                                                                                            {feature.icon}
                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                        <h3 className="text-2xl font-bold text-slate-900 mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                        {feature.title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-slate-500 leading-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {feature.description}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="mt-20 bg-gradient-to-r from-blue-700 to-slate-900 rounded-3xl p-10 md:p-14 text-white shadow-2xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="grid md:grid-cols-4 gap-10 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3 className="text-5xl font-black">500K+</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-slate-200 mt-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Happy Travellers
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h3 className="text-5xl font-black">5,000+</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-slate-200 mt-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Premium Hotels
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3 className="text-5xl font-black">180+</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-slate-200 mt-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Countries Covered
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h3 className="text-5xl font-black">24/7</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-slate-200 mt-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Premium Support
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }