import React from "react";
export default function Home() {
  return (
      <main className="min-h-screen bg-white text-gray-900">
            {/* NAVBAR */}
                  <nav className="max-w-7xl mx-auto px-6 py-6 flex items-center justify-between">
                          <h1 className="text-3xl font-extrabold text-blue-700">
                                    Stayora
                                            </h1>
                                                    <div className="hidden md:flex gap-6 text-gray-700 font-medium">
                                                              <a href="#">Hotels</a>
                                                                        <a href="#">Flights</a>
                                                                                  <a href="#">Cars</a>
                                                                                            <a href="#">Packages</a>
                                                                                                    </div>
                                                                                                            <div className="flex gap-3">
                                                                                                                      <button className="border border-gray-300 rounded-lg px-4 py-2">
                                                                                                                                  Sign In
                                                                                                                                            </button>
                                                                                                                                                      <button className="bg-blue-700 text-white rounded-lg px-4 py-2">
                                                                                                                                                                  Register
                                                                                                                                                                            </button>
                                                                                                                                                                                    </div>
                                                                                                                                                                                          </nav>
                                                                                                                                                                                                {/* HERO */}
                                                                                                                                                                                                      <section className="bg-gradient-to-br from-slate-950 via-blue-950 to-slate-900 text-white">
                                                                                                                                                                                                              <div className="max-w-7xl mx-auto px-6 py-24 grid md:grid-cols-2 gap-12 items-center">
                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                    <p className="uppercase tracking-[0.3em] text-yellow-400 mb-4">
                                                                                                                                                                                                                                                  Premium Travel Experience
                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                          <h1 className="text-5xl md:text-6xl font-extrabold mb-6 leading-tight">
                                                                                                                                                                                                                                                                                        Where will tomorrow take you?
                                                                                                                                                                                                                                                                                                    </h1>
                                                                                                                                                                                                                                                                                                                <p className="text-lg text-slate-200 mb-10">
                                                                                                                                                                                                                                                                                                                              Book luxury hotels, resorts, villas, flights, car rentals and holiday packages from one beautiful platform.
                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                      {/* SEARCH */}
                                                                                                                                                                                                                                                                                                                                                                  <div className="bg-white text-black rounded-2xl p-5 grid grid-cols-1 md:grid-cols-5 gap-3">
                                                                                                                                                                                                                                                                                                                                                                                <input className="border rounded-lg p-3" placeholder="Destination" />
                                                                                                                                                                                                                                                                                                                                                                                              <input className="border rounded-lg p-3" placeholder="Check In" />
                                                                                                                                                                                                                                                                                                                                                                                                            <input className="border rounded-lg p-3" placeholder="Check Out" />
                                                                                                                                                                                                                                                                                                                                                                                                                          <input className="border rounded-lg p-3" placeholder="Guests" />
                                                                                                                                                                                                                                                                                                                                                                                                                                        <button className="bg-blue-700 text-white rounded-lg font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                        Search
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="hidden md:block">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <img
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                src="https://images.unsplash.com/photo-1566073771259-6a8506099945?w=900&q=80"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="rounded-3xl shadow-2xl"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* FEATURED HOTELS */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <section className="max-w-7xl mx-auto px-6 py-20">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h2 className="text-3xl font-bold mb-10">Featured Hotels</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="grid md:grid-cols-4 gap-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {[
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ["Burj View Palace", "Dubai 🇦🇪", "$420/night"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ["Paris Royal Suites", "Paris 🇫🇷", "$360/night"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ["Tokyo Sky Hotel", "Tokyo 🇯🇵", "$390/night"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ["London Grand", "London 🇬🇧", "$410/night"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ].map(([name, city, price]) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div key={name} className="rounded-2xl shadow-lg overflow-hidden">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="h-40 bg-gray-200" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="p-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3 className="font-bold text-lg">{name}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-gray-500">{city}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="mt-2 font-semibold text-blue-700">{price}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button className="mt-4 w-full bg-blue-700 text-white py-2 rounded-lg">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Book
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* WHY CHOOSE */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <section className="bg-slate-900 text-white py-20 px-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="max-w-7xl mx-auto text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2 className="text-4xl font-bold mb-10">Why Choose Stayora?</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="grid md:grid-cols-3 gap-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>🏨 Premium Hotels</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>💰 Best Prices</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>🌍 Worldwide Destinations</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }